# Permalinks
permalink:      pretty

# Setup
title:          Random Thoughts
tagline:        programming & modding
url:            https://induktio.github.io
paginate:       1
baseurl:        ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:     _sass
  style:        :compressed

# About/contact
author:
  name:         Joonas Järvenpää
  email:        admin@induktio.net
  url:          https://induktio.github.io

# Custom vars
version:
github:
  repo:
      
analytics_id:   ''
disqus_id:      'induktiomods'

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
